#!/usr/bin/env bash
# Uses awk to get information about a request to a subdomain
func () {
  if [ -z "$2" ]; then
    # sub_d="www lb-01 web-01 web-02"
    # for sd in $sub_d
    # do
    # dig "$sd.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain "$sd" is a "$4" record and points to "$5""}'
    dig "www.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain www is a "$4" record and points to "$5""}'
    dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain lb-01 is a "$4" record and points to "$5""}'
    dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain web-01 is a "$4" record and points to "$5""}'
    dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain web-02 is a "$4" record and points to "$5""}'
  else
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v x="$2" '$1=x{print "The subdomain "$1" is a "$4" record and points to "$5""}'
  fi
}

func "$1" "$2"
