#!/usr/bin/env bash
# Transfer a file with scp to another machine

if [ $# -ge 5 ]
then
  sudo scp -i -o StrictHostKeyChecking=no "$4 $1 $3@$2:~/"
else
  echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
fi
