#!/usr/bin/env bash
# Installs and configure load balance server with HAProxy

#Install HAProxy
sudo apt update
sudo apt install -y --no-install-recommends software-properties-common
printf "\n" | sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt install -y haproxy=2.0\*
printf "\nENABLED=1\n" | sudo tee -a /etc/default/haproxy

# Configure HAProxy
printf "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\t server 3944-web-01 34.75.232.87:80 check\n\tserver 3944-web-02 107.23.155.109:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
