#!/usr/bin/env bash
# Installs and configure load balance server with HAProxy

#Install HAProxy
# sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get install haproxy=2.0\*
sudo  sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.back

# Configure HAProxy
printf "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\t server 3944-web-01 34.75.232.87:80 check\n\tserver 3944-web-02 107.23.155.109:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
