#!/usr/bin/env bash
# Creates a file with own PID and enters an "infinit" loop

echo $$ > /var/run/myscript.pid
trap 'echo Y U no love me?!' SIGINT
trap 'rm /var/run/myscript.pid; exit' SIGQUIT
trap 'echo I hate the kill command; rm /var/run/myscript.pid; exit' SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
