#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
txt="Best School"
idx=0

while [ $idx -lt 10 ]
do
	if [ $idx -eq 8 ]
	then
		echo "Hi"
	else
		echo "$txt"
	fi
	idx=$((idx+1))
done
