#!/usr/bin/env bash
#Superstitious numbers from 1 to 20

idx=1

while [ $idx -le 20 ]
do
	echo "$idx"
	idx=$((idx+1))

	if [ $idx -eq 5 ]
	then
		echo "bad luck from China"
		continue
	elif [ $idx -eq 10 ]
	then
		echo "bad luck from Japan"
	elif [ $idx -eq 18 ]
	then
		echo "bad luck from Italy"
	fi

done
