#!/usr/bin/env bash
#Superstitious numbers from 1 to 20

idx=1

while [ $idx -le 20 ]
do
	echo "$idx"
	idx=$((idx+1))

	case $idx in
		5)
			echo "bad luck from China"
		;;
		10)
			echo "bad luck from Japan"
		;;
		18)
			echo "bad luck from Italy"
		;;
	esac
done
