#!/usr/bin/env bash
#Checks existance type and content of file school

FILE=./school

if test -e "$FILE"
then
	echo "school file exist"

	if test -f "$FILE"
	then
		if [ "$(wc -c < $"$FILE")" -gt 0 ]
		then
			echo "school file is not empty"
		else
			echo "school file is empty"
		fi

		echo "school is a regular file"
	else
		echo "school file is not empty"
	fi
else
	echo "school file does not exist"
fi
