#!/usr/bin/env bash
# Sets up the firewall so that fowards from port 8080 to port 80
sudo ufw allow 8080
# ufw forwarding
sudo sed -i '1s/^/*nat\n:PREROUTING ACCEPT [0:0]\n-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\nCOMMIT\n/' /etc/ufw/before.rules
# systemctl allow ipv4 forward
sudo sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf
sudo sysctl -p

sudo service ufw restart
echo "y" | sudo ufw enable
