#!/usr/bin/env bash
# Changes localhost IP and facebook.com IP for google.com IP

cat /etc/hosts > ./hosts.new
sed -i 's/[0-9]\+.[0-9]\+.[0-9]\+.[0-9]\+\s\+localhost/128.0.0.2\tlocalhost/' ./hosts.new

if grep -q "facebook.com" ./hosts.new
then
	sed -i 's/[0-9]\+.[0-9]\+.[0-9]\+.[0-9]\+\s\+facebook.com/8.8.8.8\tfacebook.com/' ./hosts.new
else
	"8.8.8.8	facebook.com" >> ./hosts.new
fi
cp ./hosts.new /etc/hosts
rm ./hosts.new
