#!/usr/bin/env bash
#Changes nginx config so that its run by the nginx server
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo service nginx restart
